---
- include_role:
    name: geerlingguy.docker

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Ubuntu.yml
  when: ansible_os_family == 'Ubuntu'

- name: install docker-py
  shell: pip install docker-py
  become: true
