---
- include_role:
    name: geerlingguy.docker

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: upgrade pip
  pip: 
    name: pip
    state: latest
  become: true

- name: install docker
  pip:
    name: docker
  become: true
